# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d5e9db11e3e56a7bd2c0bfc98aa9497eed6a611b4a7e100bd31322c531bd37800322a5091fe2e96a3172a3a0cb6d84b1bdd8e34ba04cd713283a07d7d7812f5

test:
  secret_key_base: ebe7183f23c98ea2137cd50bd47f40ea2f00f609918bbc9a14a849be4e0222be80c8f422b4e9c44ebb0eb275157421ed3234d38c6be0d2755c0536d98fcd4af3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
